name: submit

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  resubmit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [stable, testing, unstable]
    permissions:
      contents: write
    steps:
      - name: submit
        uses: manjaro-contrib/action-submit@b1d2fcb95dee2b2be1d0565b62cf0cbb55fc0977 # main
        with:
          dispatch-target: ${{ vars.PACKAGES_REPO }}
          dispatch-token: ${{ secrets.DISPATCH_TOKEN }}
          branch: ${{ matrix.branch }}
